dataset: 'JetClass'
model: 'ParticleTransformer'

rnd_seed: 42
num_epochs: 30
lr: 0.001

DataModule:
  num_train: 100000
  num_valid: 10000
  num_test: 10000
  batch_size: 256

JetNet:
  pad_num_ptcs: 30

JetClass:
  pad_num_ptcs: 64
  num_root: 2