dataset: 'JetNet'
model: 'ParticleTransformer'

rnd_seed: 42
num_epochs: 30
lr: 0.001

DataModule:
  num_train: 100000
  num_valid: 10000
  num_test: 10000
  batch_size: 256

JetNet:
  pad_num_ptcs: 30
  dash_features: ['log_part_pt', 'part_deta', 'part_dphi']

JetClass:
  pad_num_ptcs: 64
  num_root: 2
  dash_features: [
    'log_part_pt', 'log_part_E', 'part_deta', 'part_dR',
    'part_charge', 'part_isElectron', 'part_isMuon', 'part_isPhoton',
    'part_isChargedHadron', 'part_isNeutralHadron',
  ]